Repository umr-lops/xsar, pull requests merged in 2023-05, with the labels that each got.

#159 handle empty intersection of the landmask with SAR image
  src/xsar/base_meta.py
Labels: bug

#160 Extract Sentinel-1 Reader
  README.md
  docs/_static/uml/classes_all_attributes.png
  docs/_static/uml/packages_all_attributes.png
  docs/examples/mask.ipynb
  docs/examples/rcm.ipynb
  docs/examples/xsar.ipynb
  docs/examples/xsar_advanced.ipynb
  docs/installing.rst
  environment.yml
  requirements_doc.txt
  setup.py
  src/scripts/compress_safe.py
  src/xsar/base_dataset.py
  src/xsar/radarsat2_dataset.py
  src/xsar/radarsat2_meta.py
  src/xsar/rcm_dataset.py
  src/xsar/sentinel1_dataset.py
  src/xsar/sentinel1_meta.py
  src/xsar/sentinel1_xml_mappings.py
  src/xsar/utils.py
  src/xsar/xml_parser.py
  src/xsar/xsar.py
Labels: enhancement

#162 Minor workflow tuning
  .github/actions/dynamic_matrix.py
Labels: dependencies
