Repository umr-lops/xsar, pull requests merged in 2023-06, with the labels that each got.

#167 Homogene render of start and stop date
  src/xsar/base_meta.py
Labels: bug

#168 add a worfklow to publish to pypi on release
  .github/workflows/publish.yml
Labels: enhancement

#169 try to fix the error from pypi
  setup.py
Labels: bug, documentation

#170 small revisions of the readme
  README.md
Labels: documentation
