Repository umr-lops/xsar, pull requests merged in 2024-11, with the labels that each got.

#232 Replace `xarray-datatree` by `xarray.datatree`
  .pre-commit-config.yaml
  requirements.txt
  setup.py
  src/xsar/__init__.py
  src/xsar/base_dataset.py
  src/xsar/base_meta.py
  src/xsar/ipython_backends.py
  src/xsar/radarsat2_dataset.py
  src/xsar/radarsat2_meta.py
  src/xsar/raster_readers.py
  src/xsar/rcm_dataset.py
  src/xsar/rcm_meta.py
  src/xsar/sentinel1_dataset.py
  src/xsar/sentinel1_meta.py
  src/xsar/utils.py
  src/xsar/xarray_backends.py
  src/xsar/xsar.py
Labels: enhancement

#234 fix a bug with rcm imports
  src/xsar/__init__.py
  src/xsar/radarsat2_meta.py
Labels: bug

#235 move from `setup.py` to `pyproject.toml` + CI improvements
  .github/release.yml
  .github/workflows/ci.yaml
  .github/workflows/upstream-dev.yaml
  ci/install-upstream-dev.sh
  ci/requirements/docs.yaml
  ci/requirements/environment.yaml
  pyproject.toml
  setup.py
  src/xsar/__init__.py
Labels: enhancement

#239 add missing method `get_test_file`
  src/xsar/__init__.py
Labels: bug

#230 Better gestion of error for recalibration
  src/xsar/config.yml
  src/xsar/raster_readers.py
  src/xsar/rcm_dataset.py
  src/xsar/sentinel1_dataset.py
Labels: bug

#243 activate unit tests in pull requests
  .github/workflows/ci.yaml
  ci/requirements/environment.yaml
Labels: bug, enhancement

#246 homogeneous code for the denoising of the three sensors
  src/xsar/radarsat2_dataset.py
  src/xsar/sentinel1_dataset.py
Labels: enhancement
